spring.application.name=order-service
spring.config.import=optional:configserver:http://localhost:8092
user.service.url=http://localhost:8083/api/v1/addresses
cart.service.url=http://localhost:8089/api/v1/carts/internal
inventory.service.url=http://localhost:8087/api/v1/inventories


